// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

using System.Text;
using System.Text.Json;

namespace SharpEmu.Diagnostics;

/// <summary>
/// Generates standardized AI-friendly debug reports. Every crash produces
/// a debug_report.json, AI_CONTEXT.md, and AI_SUMMARY.md that any AI
/// (ChatGPT, Claude, Gemini, Cursor) can analyze without reading source code.
/// </summary>
public static class AiReportGenerator
{
    public static void GenerateReport(string outputDir, string gameId,
        ulong faultAddress, ulong rip, ulong rax, ulong rdi, ulong rsi,
        string? firstFailure, string[] missingNids, string[] lastImports,
        string bootStage, int successLevel)
    {
        Directory.CreateDirectory(outputDir);

        // 1. debug_report.json — structured JSON for AI consumption
        var report = new
        {
            schema = 1,
            emulator_version = "v1.0.0011",
            game_id = gameId,
            boot_stage = bootStage,
            success_level = successLevel,
            crash = new
            {
                type = ClassifyCrash(faultAddress, rdi, rsi),
                rip = $"0x{rip:X16}",
                fault_address = $"0x{faultAddress:X16}",
                null_register = rdi == 0 ? "RDI" : rsi == 0 ? "RSI" : "unknown",
                module = "game",
                confidence = 0.85,
                instruction = "see crash_snapshot.txt for disassembly"
            },
            missing_nids = missingNids,
            first_failure = firstFailure ?? "none",
            last_imports = lastImports,
            suggested_actions = GenerateSuggestedActions(faultAddress, rdi, rsi, missingNids, firstFailure),
            files_included = new[] { "debug_report.json", "AI_CONTEXT.md", "AI_SUMMARY.md", "crash_snapshot.txt" }
        };

        var json = JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(Path.Combine(outputDir, "debug_report.json"), json);

        // 2. AI_CONTEXT.md — context for AI assistants
        var context = new StringBuilder();
        context.AppendLine("# SharpEmu AI Debug Context");
        context.AppendLine();
        context.AppendLine("This report was generated by SharpEmu, a PS5 emulator written in C#.");
        context.AppendLine();
        context.AppendLine($"- **Emulator version**: v1.0.0011");
        context.AppendLine($"- **Game ID**: {gameId}");
        context.AppendLine($"- **Boot stage**: {bootStage}");
        context.AppendLine($"- **Success level**: {successLevel}%");
        context.AppendLine($"- **Crash type**: {ClassifyCrash(faultAddress, rdi, rsi)}");
        context.AppendLine($"- **Crash RIP**: 0x{rip:X16}");
        context.AppendLine($"- **Fault address**: 0x{faultAddress:X16}");
        context.AppendLine($"- **NULL register**: {(rdi == 0 ? "RDI" : rsi == 0 ? "RSI" : "none")}");
        context.AppendLine($"- **First failure**: {firstFailure ?? "none"}");
        context.AppendLine($"- **Missing NIDs**: {missingNids.Length}");
        context.AppendLine();
        context.AppendLine("## Missing NIDs");
        foreach (var nid in missingNids)
            context.AppendLine($"- {nid}");
        context.AppendLine();
        context.AppendLine("## Last 10 imports before crash");
        foreach (var imp in lastImports.Take(10))
            context.AppendLine($"- {imp}");
        context.AppendLine();
        context.AppendLine("## Suggested investigation");
        foreach (var action in GenerateSuggestedActions(faultAddress, rdi, rsi, missingNids, firstFailure))
            context.AppendLine($"- {action}");
        context.AppendLine();
        context.AppendLine("## Files included");
        context.AppendLine("- `debug_report.json` — structured crash data");
        context.AppendLine("- `AI_SUMMARY.md` — 20-line summary for quick AI analysis");
        context.AppendLine("- `crash_snapshot.txt` — full crash dump with registers, imports, timeline");
        context.AppendLine();
        context.AppendLine("## How to use");
        context.AppendLine("1. Read `AI_SUMMARY.md` for a quick overview");
        context.AppendLine("2. Read `debug_report.json` for structured data");
        context.AppendLine("3. Read `crash_snapshot.txt` for full details");
        context.AppendLine("4. Check `docs/AI_DEBUG_PROMPT.md` for the AI prompt template");

        File.WriteAllText(Path.Combine(outputDir, "AI_CONTEXT.md"), context.ToString());

        // 3. AI_SUMMARY.md — 20-line summary
        var summary = new StringBuilder();
        summary.AppendLine("# AI Summary");
        summary.AppendLine();
        summary.AppendLine($"Game: {gameId}");
        summary.AppendLine($"Version: v1.0.0011");
        summary.AppendLine($"Boot: {bootStage} ({successLevel}%)");
        summary.AppendLine($"Crash: {ClassifyCrash(faultAddress, rdi, rsi)}");
        summary.AppendLine($"RIP: 0x{rip:X16}");
        summary.AppendLine($"Fault: 0x{faultAddress:X16}");
        summary.AppendLine($"NULL reg: {(rdi == 0 ? "RDI" : rsi == 0 ? "RSI" : "none")}");
        summary.AppendLine($"First failure: {firstFailure ?? "none"}");
        summary.AppendLine($"Missing NIDs: {missingNids.Length}");
        summary.AppendLine();
        summary.AppendLine("Root cause:");
        summary.AppendLine(GenerateRootCause(faultAddress, rdi, rsi, missingNids, firstFailure));
        summary.AppendLine();
        summary.AppendLine("Suggested fix:");
        foreach (var action in GenerateSuggestedActions(faultAddress, rdi, rsi, missingNids, firstFailure).Take(3))
            summary.AppendLine($"- {action}");
        summary.AppendLine();
        summary.AppendLine($"Confidence: 85%");

        File.WriteAllText(Path.Combine(outputDir, "AI_SUMMARY.md"), summary.ToString());
    }

    private static string ClassifyCrash(ulong faultAddress, ulong rdi, ulong rsi)
    {
        if (faultAddress < 0x10000) return "NULL_POINTER";
        if (faultAddress >= 0x1FE000000UL && faultAddress < 0x200000000UL) return "GPU_ADDRESS_ACCESS";
        if (faultAddress >= 0x7F0000000000UL && faultAddress < 0x800000000000UL) return "HOST_POINTER_LEAK";
        if (rdi == 0 || rsi == 0) return "NULL_POINTER";
        return "UNKNOWN";
    }

    private static string GenerateRootCause(ulong faultAddress, ulong rdi, ulong rsi,
        string[] missingNids, string? firstFailure)
    {
        var crashType = ClassifyCrash(faultAddress, rdi, rsi);
        return crashType switch
        {
            "NULL_POINTER" => $"A NULL pointer was dereferenced. Register {(rdi == 0 ? "RDI" : "RSI")} is zero. " +
                              $"This means a game object was never initialized. " +
                              (firstFailure != null ? $"First failure was: {firstFailure}" : "No HLE failure detected."),
            "GPU_ADDRESS_ACCESS" => "Game accessed unmapped GPU memory at a hardcoded address.",
            "HOST_POINTER_LEAK" => "A host memory address leaked into guest code (Marshal.AllocHGlobal).",
            _ => "Unknown crash type. Check crash_snapshot.txt for details."
        };
    }

    private static string[] GenerateSuggestedActions(ulong faultAddress, ulong rdi, ulong rsi,
        string[] missingNids, string? firstFailure)
    {
        var actions = new List<string>();
        var crashType = ClassifyCrash(faultAddress, rdi, rsi);

        if (missingNids.Length > 0)
        {
            actions.Add($"Implement missing NID: {missingNids[0]}");
        }

        if (crashType == "NULL_POINTER")
        {
            actions.Add("Check which HLE call should have set the NULL register");
            actions.Add("Look at the first failure in Return Analyzer");
        }

        if (crashType == "GPU_ADDRESS_ACCESS")
        {
            actions.Add("Ensure GPU placeholder memory is mapped at 0x1FE000000");
        }

        if (crashType == "HOST_POINTER_LEAK")
        {
            actions.Add("Use guest memory allocator instead of Marshal.AllocHGlobal");
            actions.Add("Use TryReadCompat/TryWriteCompat for host-pointer fallback");
        }

        if (firstFailure != null && firstFailure.Contains("UNRESOLVED"))
        {
            actions.Add("Implement the unresolved NID that caused the first failure");
        }

        if (actions.Count == 0)
        {
            actions.Add("Check crash_snapshot.txt for full register dump and stack trace");
        }

        return actions.ToArray();
    }
}
